set -g mouse on
set -g allow-passthrough on
set -gq extended-keys on
set -g set-clipboard on
set -ga terminal-overrides ",*:OSC8"
set -g default-terminal "ghostty"
set -ga terminal-overrides ",ghostty:Tc"
