#!/bin/sh

cd $HOME/config

for base in `find . -name '.??*' -type f |grep  -v '.#\|~$' | sed 's@^./@@g'`; do
    rm -f $HOME/$base
    # copy it first to have the right permissions
    cp -v $base $HOME/$base
    sed -e "s%@HOME@%$HOME%g" < $base > $HOME/$base
done

# ssh specific
if [ ! -d $HOME/.ssh ]; then
    mkdir $HOME/.ssh
    chmod go-w $HOME/.ssh
fi

cp -v .ssh/config $HOME/.ssh/
chmod go-w $HOME/.ssh/config

# icewm specific
if [ ! -d $HOME/.icewm ]; then
    mkdir $HOME/.icewm
fi

cp -v .icewm/preferences $HOME/.icewm/

# liquidprompt and git specific
if [ ! -d $HOME/.config/git ]; then
    mkdir -p $HOME/.config/git
fi

cp -v .config/liquidpromptrc $HOME/.config/
cp -v .config/git/ignore $HOME/.config/git/

# install ends here
