#!//bin/sh
## Get/Save ssh environement.
# Chmouel Boudjnah <chmouel@mandrakesoft.com>

if [ ! -r "$HOME/.ssh/identity" ]; then
    return
fi

SINFO=$HOME/.ssh/info.`uname -n`

[[ -f $SINFO ]] && source $SINFO

if [[ -n $SSH_AUTH_SOCK ]];then
    if [[ ! -e $SSH_AUTH_SOCK ]];then
	unset SSH_AUTH_SOCK
	rm -f $SINFO
    else
	echo SSH_AUTH_SOCK=$SSH_AUTH_SOCK > $SINFO
    fi
fi

if [[ -n $SSH_AGENT_PID ]];then
    if [[ -z $(ps --no-header -p $SSH_AGENT_PID) || -z $SSH_AUTH_SOCK ]];then
	unset SSH_AGENT_PID
	rm -f $SINFO
    else
	echo SSH_AGENT_PID=$SSH_AGENT_PID >> $SINFO
    fi
fi

if [[ -z $SSH_AUTH_SOCK || -z $SSH_AGENT_PID ]];then
    rm -f $SINFO
fi

if [[ ! -f $SINFO ]];then
    ssh-agent > $SINFO
    . $SINFO
fi

export SSH_AGENT_PID SSH_AUTH_SOCK

# ask the pass phrase only in interactive session
if [ -n "$PS1" -a -n "$SSH_AUTH_SOCK" ]
then
    # test if the agent has already an identity
    ssh-add -l | fgrep -i 'no identit' > /dev/null 2>&1

    # if not try to add the default one
    if [ $? == 0 ]; then
	if [ -z "$DISPLAY" ]; then
	    ssh-add
	else
	    ssh-add < /dev/null
	fi
    fi
fi
