#!/bin/sh
#---------------------------------------------------------------
# Project         : personal config
# Module          : config
# File            : run-ssh
# Version         : $Id: run-ssh,v 1.4 2001-12-30 04:13:03 flepied Exp $
# Author          : Frederic Lepied
# Created On      : Sat Dec 29 21:16:37 2001
# Purpose         : Get/Save ssh environement.
#---------------------------------------------------------------

if [ -n "$SSH_AUTH_SOCK" ];then
    if [ ! -e "$SSH_AUTH_SOCK" ];then
        unset SSH_AUTH_SOCK
    else
	return
    fi
fi

SINFO=$HOME/.ssh/info.`uname -n`

[ -f $SINFO ] && . $SINFO

ssh-add -l > /dev/null 2>&1

if [ $? != 0 ];then
    [ -n "$PS1" ] && echo "No agent, removing $SINFO"
    rm -f $SINFO
fi

if [ ! -f $SINFO ];then
    ssh-agent | fgrep -v echo > $SINFO
    . $SINFO
fi

export SSH_AGENT_PID SSH_AUTH_SOCK

# ask the pass phrase only in interactive session
if [ -n "$PS1" -a -n "$SSH_AUTH_SOCK" ]
then
    # test if the agent has already an identity
    ssh-add -l | fgrep -i 'no identit' > /dev/null 2>&1

    # if not try to add the default one
    if [ $? == 0 ]; then
	KEY=

	for k in $HOME/.ssh/id_dsa $HOME/.ssh/id_dsa $HOME/.ssh/identity; do
	    if [ -r $k ]; then
		KEY=$k
		break
	    fi
	done

	if [ -z "$KEY" ]; then
	    return
	fi

	if [ -z "$DISPLAY" ]; then
	    ssh-add $KEY
	else
	    ssh-add $KEY < /dev/null
	fi
    fi
fi

# run-ssh ends here
